### ISSUE TITLE
Choosing Exit installs HENkaku

### ISSUE THREAD

**Issue by fumu-no-kagomeko** [TheOfficialFloW/h-encore#10]
When the app is started and `Exit` is chosen, the expoit is installed regardless. As an end-user, _ expected the application to close without doing anything. There is an `Install HENkaku` option there too, you know.

**Comment by TheOfficialFloW** [comment]
If I did it this way people would also be confused and ask why their console is not hacked yet. It's only installed the first time so whatever.
