### ISSUE TITLE
What type of  memory card (SD) do I need for OLED model (psv1000) ?

### ISSUE THREAD

**Issue by kaedea** [TheOfficialFloW/h-encore#105]
I got the original card lost with my psv 1000, so I am considering to buy a new one.
Can I just buy a 3rd-party SD card instead, such as Sandisk ?

**Comment by theAkito** [comment]
1. This is not the place for such questions. You should use a forum, instead. Playstation related communities are for example pretty active on Reddit.
2. You need the PS Vita microSD to PS Vita adapter. Then you put in a microSD card into the adapter and the adapter, obviously, into the PS Vita's game card slot.

However, this is not a replacement for the original proprietary memory card for PS Vita, which goes into the smaller memory card slot, which is **NOT** the game card slot. If you need to patch your PS Vita, you will need an original PS Vita memory card.

However, looking at your story, I would suggest you to not buy another one. If you are so careless, that you lose such important equipment, you might as well lose your head at some point too, and perhaps not even notice.

**Comment by TheOfficialFloW** [comment]
Closed and blocked.
