### ISSUE TITLE
*PSVITA Will not connect to PC/QCMA* 

### ISSUE THREAD

**Issue by michaelbwwfc** [TheOfficialFloW/h-encore#12]
Hello,I have tried connecting the PSVITA to the PC through the USB and WIFI but I keep getting errors I am running 3.67

**Comment by DrkShinigami** [comment]
Put the vita on plane mode, i lost almost 2 hours getting the update system error while trying to connect to pc but the problem can be solved with plane mode, by the way i´m at 3.65

**Comment by michaelbwwfc** [comment]
Tried it but still doesn't work :(

**Comment by noahc3** [comment]
If your PC isn't detecting your Vita, try reinstalling QCMA and choose a different USB driver during the installation.

**Comment by azizul92** [comment]
im also having issues with this tried a few different drivers but still no luck

**Comment by TheOfficialFloW** [comment]
not h-encore issue?
