### ISSUE TITLE
Henkaku Settings not available in Settings app after install

### ISSUE THREAD

**Issue by JK3Y** [TheOfficialFloW/h-encore#14]
I was on 3.65 enso.
I decided to update to 3.68 and I used the FWUpdater app. I ran into [this issue](https://github.com/TheOfficialFloW/fwupdater/issues/1) and after following the instructions I was able to update to 3.68.

So far so good...
After launching h-encore and installing henkaku my settings app does not list "Henkaku Settings" where the "System Update" option is. It also lists my FW as 3.67 after h-encore is enabled. Before it's enabled my vita reports that it's on 3.68.

This isn't affecting the hack; homebrew continues to work as it should, but it is strange behavior that I haven't seen mentioned anywhere yet.

**Comment by TheOfficialFloW** [comment]
Not mentioned anywhere: https://github.com/TheOfficialFloW/h-encore/blob/master/README.md#henkaku-settings

**Comment by JK3Y** [comment]
Under the instructions for removing the alert before hencore loads you specifically say go to henkaku settings. I don't have henkaku settings after following the method described above

**Comment by ms2048** [comment]
Do you have listed ur0:tai/henkaku.suprx under sections *main, *NPXS10015 and *NPXS10016 in your active tai/config.txt?

I had exactly the same behavior, as I have copied config.txt from the previous Vita (3.65 enso updated from 3.60) and somehow these entries were missing there. **Re-adding these entries fixed this problem** for me.

If you're not sure you can use the 'reset taiHEN config.txt' option (mentioned in the readme) from within h-encore itself and take a closer look at the default config.txt.
