### ISSUE TITLE
What will happen if I install enso on the incorrect version.

### ISSUE THREAD

**Issue by lunalik2** [TheOfficialFloW/h-encore#15]
I have done something weird, and for whatever reason, my vita displays as 3.65, but says it's on the latest version and can even connect online without henkaku. According to vitaident, my vita has a firm ver of 3.65, but a sys ver of 3.68. If the enso installer is incompatible, will it just give an error, or cause irreversible damage?

**Comment by TheOfficialFloW** [comment]
It will see that the os0 crc doesn't match and abort if you're on the wrong fw.

**Comment by lunalik2** [comment]
thanks
