### ISSUE TITLE
VitaShell download fails with vague error message if airplane mode enabled.

### ISSUE THREAD

**Issue by noahc3** [TheOfficialFloW/h-encore#18]
Unsure if this is the intended functionality. If you try to download Vitashell with flight mode enabled, it throws error 0x80412112. If only Wifi is disabled, it asks to enable wifi.

If this is intended functionality, or cannot be worked around, a possible enhancement could be to substitute the vague error message with a request to disable airplane mode and retry.

**Comment by CelesteBlue-dev** [comment]
Could be improved by adding a message to say airplane mode must be disabled when it is enabled
Or maybe use a system function that displays flight mode system dialog.
I think this is used in VitaShell.

**Comment by TheOfficialFloW** [comment]
I don't want to add an user error message.

**Comment by darkralts** [comment]
lol
