### ISSUE TITLE
C2-12858-4 while copying [SOLVED]

### ISSUE THREAD

**Issue by whydoidothism8** [TheOfficialFloW/h-encore#2]
I just did everything normally and when it nearly finished it gave me this error

**Comment by Luro02** [comment]
that issue is useless !
please provide a bit more information on your problem ?
what did you do ?
can you reproduce the error ?

**Comment by whydoidothism8** [comment]
here,described it

**Comment by TheOfficialFloW** [comment]
I guess the cause of this issue is that one of the folders was not encrypted properly.

**Comment by HYXHost** [comment]
Yes as FloW mentioned you need to re-encrypt the files and try again. I had this error too and retried encrypting and it works now fully installed!

**Comment by whydoidothism8** [comment]
i did too

**Comment by Ziiella** [comment]
You will probably want to try a couple times. I had to do it about 8 times myself before it decided to work. So your best bet would be to keep trying.

**Comment by xPandamon** [comment]
So you just repeat steps 9-11 until it works? Getting the same error and i definitly didn't do anything wrong.

**Comment by xPandamon** [comment]
Tried it atleast 3 time from beginning to finish now. Always getting C2-12858-4 when trying to transfer it and i'm 100% positive i didn't fuck it up.

**Comment by Hellghast** [comment]
This is all due to the fact that after trinity did not update the database in qcma
