### ISSUE TITLE
SD2VITA not loading after installing henkaku

### ISSUE THREAD

**Issue by cloudstrife999** [TheOfficialFloW/h-encore#21]
Updated plugins GAMESD.skprx  but no luck... sd2vita adapter is working fine but memory card is not being detected.

**Comment by leocmp** [comment]
Try to use the StorageMgr plugin the same has already been updated for all versions. I had the same problem.

**Comment by cloudstrife999** [comment]
Storagemgr isnt loading UX0 on hencore boot so i mount SD2VITA in vitashell. Please note this is only in 3.68.

**Comment by Rameron** [comment]
Are you using sd2vita driver for 3.68? You can get it in my git.

**Comment by cloudstrife999** [comment]
Thanks, i found out the problem. I was gamesd.skpx old version. We have to use v3.0 to enable auto sd2vita mounting on h-encore 3.68
