### ISSUE TITLE
C1-2758-2 when transferring

### ISSUE THREAD

**Issue by TentacleMonster** [TheOfficialFloW/h-encore#22]
I've been trying to transfer h-encore over to my vita for two days now.
I did everything by tutorial several times, no luck.
Same with auto h-encore, the same error when i try to transfer.
Every step before that was fine, but no matter what it doesn't want to transfer.
Neither wi-fi nor usb transfers work.
My official firmware version is 6.68, and Vita itself is an old fat 3G+Wi-fi version.
I also tried rebuilding the database and formatting several times, still no luck.

**Comment by Rameron** [comment]
Your memory card can be broken. Try to use another memory card.

**Comment by justhereforasolution** [comment]
Same issue here (fat model, 3.65). I tested the memory card and it works fine, so it must be something else.

**Comment by Reverand** [comment]
I am using two different memory cards on two different systems, and both are resulting in the same C1-2758-2 error.  Guide was followed, as well as a video to ensure I was following the correct steps.  3.68 OFW on a Fat and Slim, setup on my PSN account, same error on each.

Please let me know what else I can provide to assist with further troubleshooting.

**Comment by Ludburghmdm** [comment]
Same issue here; Japanese PS Vita Slim on 3.65.
Using Linux and followed both the official readme.md tutorial and the vita.hacks.guide tutorial; both exhibited the same C1-2758-2 error upon attempting to transfer. Also tried rebuilding database, removing the memory card, reinserting the memory card; compiling different versions of QCMA, no dice :(

**Comment by alx365** [comment]
Sorry to comment on a two year old issue, but i am having the same issue

**Comment by lovenemesis** [comment]
Sorry to comment on an issue that half an decade ago. But this is still happening today.

I was following [the tutorial](https://wololo.net/vita-cfw4dummies/) step by step exactly and got the same error during transferring the packaged h-encore while I had no problem transfer any other Apps between my Vita and Fedora system.
Initially I thought it was permission issue. But exactingly all content shared the same permission setup as the rest of qcma backed up apps. Hence no clue what could cause this.

Eventually I had to dig out another Win machine to workaround the problem, just as OP.
