### ISSUE TITLE
vita shell fails to download 

### ISSUE THREAD

**Issue by amaksims** [TheOfficialFloW/h-encore#25]
i get the error message of "0x80af5025"
is there a way to fix this

**Comment by Rameron** [comment]
Did you move a lot of small files to the memcard? I heard It would be the reason. Anyway you can just to try backup your data and to format your card.

**Comment by LoungeKatt** [comment]
You have to open Settings > Henkaku Settings > (Check) Enable Unsafe Homebrew

**Comment by kujiko** [comment]
Ok, so even with unsafe homebrew enabled, and a fresh memcard, I'm still getting this error.

**Comment by yingdongzhang** [comment]
@kujiko 

Try a different wifi or use your phone as a hotspot. I had the same issue and using my phone as a wifi hotspot worked.

**Comment by kujiko** [comment]
The only issue there is that I don't have a wifi hotspot on my phone.

**Comment by yingdongzhang** [comment]
@kujiko  really? What phone are you using?

**Comment by yingdongzhang** [comment]
@kujiko  Nokia 6 runs Android right? Do you have a cellular data plan that allows your phone to connect to 4G or LTE network? If you do you can use your phone as a wifi hotspot. Just go to settings -> Network & Internet -> Hotspot & tethering -> Set up Wi-Fi hotspot. Enter a name, choose WAP2-PSK for security, enter a password, then turn on Wi-Fi hotspot. Then you can connect your PS Vita to the wi-fi hotspot on your phone.

**Comment by hooman-pro** [comment]
also i have this problem. and by using mobile hotspot it also get error and not download vita shell !
is there any way for install it directly by content manager? or an other way?

**Comment by seewood** [comment]
For everyone who get this error. Reset your DNS settings from Update to Firmware 3.65! Set ist Back to "Auto" this should solve the issue.

**Comment by hooman-pro** [comment]
I used an android rooted device to share vpn and it workd!

**Comment by NavyGhost02** [comment]
I have an issue I have 718mb available and I just bought a 8gb Sony Memory card in order to download VitaShell, am I the only one with this issue ? Please help
