### ISSUE TITLE
Size of H-encore bubble

### ISSUE THREAD

**Issue by fovdj** [TheOfficialFloW/h-encore#26]
Hey.. Please give me advice...

I have already run command psvimg-create and get file X.psvimg and X.psvmd, but the size of file X.psvimg is around 243 Mb..

So size of H-encore bubble when I want copy to my PS Vita is about 900 Mb.. 

Please give me advice what should I do.. Thanks

**Comment by Sir-Charles** [comment]
I noticed something similar, not sure if the same issue..

When transfer in the content manager app completed, the h-encore app size is shown correctly as 243mb, but when I exit and check the h-encore bubble size through the Live Area my bubble size was around 160mb so I deleted it and transferred again, this time it's 266mb which seemed close enough so I ran it and it works no problem.

Going back into content manager and "manage content on memory card" now also shows it as 266mb.

**Comment by ms2048** [comment]
The total size of `h-encore/PCSG90096` created in step 9 should be 254,568,713 bytes. I don't know whether the exact size depends on the AID used but if yours is around 900MB instead then you probably did step 9 wrong.
