### ISSUE TITLE
Can not reinstall h-encore

### ISSUE THREAD

**Issue by wang80919** [TheOfficialFloW/h-encore#27]
PSV2000
Use PSV MemoryCard to Install h-encore , it is ok.
Remove PSV MemoryCard , Resstart PSV,  Now it is use Inside Stroage.
I want ReInstall again, but ,can not transfer to PSV.
It get the error You can only copy applications that your account is the owner of.
I think , When installed HENkaku, this issue will show.

please make a  key for Hacked.
a key for No Hacked.

**Comment by RY0M43CH1Z3N** [comment]
Step 8 again, because you "unlinked" your memory card.

**Comment by wang80919** [comment]
AID not changed.
I delete my PS Vita folder all dir and file.
but same AID folder created.

**Comment by wang80919** [comment]
how to reopen this.
