### ISSUE TITLE
C0-11136-2 when Launching

### ISSUE THREAD

**Issue by cr0bar** [TheOfficialFloW/h-encore#3]
I've followed the instructions from top to bottom twice and on both attempts received the following error after answering 'Yes' to the trophy message:

`Cannot start this application.
You must download the application again from [Download List] in [PS Store].
(C0-11136-2)`

Original PSVita with 3.65 firmware.

**Comment by TheOfficialFloW** [comment]
Seems like the license file is not correct.

**Comment by cr0bar** [comment]
No joy... 3rd time round, same error.

**Comment by devingDev** [comment]
you prob forgot this by reading too fast:

and rename the just pasted file temp.bin to 6488b73b912a753a492e2714e9b38bc7.rif


happened to me too lul

**Comment by cr0bar** [comment]
Decided to follow the guide on Windows rather than on my Mac and works fine!

**Comment by cr0bar** [comment]
@devingDev I definitely renamed the temp file on my 3 mac attempts.

**Comment by Adhrast** [comment]
Giving me the same error, I'm on Mac :/ and I copied and renamed the license file, I'd like to know what I did wrong :/

**Comment by elporfirio** [comment]
TO ALL MAC USERS:

Verify that the file has the correct extension, check on terminal with command: ls
maybe you have XXXXX.rif.bin instead only XXXXX.rif

For Finder:

Preferences > Advance > Check First option "Show extension on File names" (some like that I have in spanish)

Redo sequence and that should work.

**Comment by explosivo2k2** [comment]
@elporfirio This was certainly my issue. Didn't even realize I still had file extensions hidden. Thanks for this! Working now.

**Comment by Adhrast** [comment]
@elporfirio I’m pretty sure I have the extensions ebanked, I’m gonna check as soon as I get home

**Comment by CelesteBlue-dev** [comment]
@TheOfficialFloW you can close this issue. thanks.

**Comment by lordfriky** [comment]
For some reason, I'm still having that issue...
I've already renamed temp.bin to 6488b73b912a753a492e2714e9b38bc7.rif using Finder, using `mv "temp.bin" "6488b73b912a753a492e2714e9b38bc7.rif"` and even with @elporfirio solution and nothing yet :/

**Comment by JonnieBoy18** [comment]
I need help, im on a Windows PC and i tried doing all the steps, my temp.bin folder is now a 6488b73b912a753a492e2714e9b38bc7.rif file. I refreshed the database. I'm just lost now. Can someone please help me. My PS Vita is on version 3.67.

**Comment by CapitanZ27** [comment]
You Need upgrade to 3,68v 

Enviado desde mi iPhone

El jul. 9, 2018, a la(s) 8:14 p. m., JonnieBoy18 <notifications@github.com> escribió:

> I need help, im on a Windows PC and i tried doing all the steps, my temp.bin folder is now a 6488b73b912a753a492e2714e9b38bc7.rif file. I refreshed the database. I'm just lost now. Can someone please help me. My PS Vita is on version 3.67.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 




*
*

*
*

*Declinación de Responsabilidades:* Los servicios de MISENA 
son soportados tecnológicamente por © Google y ofrecidos por el Servicio 
Nacional de Aprendizaje – SENA de manera gratuita a los aprendices e 
instructores de programas de formación titulada, las opiniones que contenga 
este mensaje son exclusivas de su autor y no representan la opinión del 
Servicio Nacional de Aprendizaje o de sus autoridades. El receptor deberá 
verificar posibles virus informáticos que tenga el correo o cualquier 
anexo, razón por la cual el SENA no es responsable de los daños causados 
por cualquier virus transmitido en este correo electrónico.

Los 
contenidos, textos, imágenes, archivos enviados en este mensaje son 
responsabilidad exclusiva del remitente y no reflejan ni comprometen de 
ninguna manera a la institución. No se autoriza el uso de esta herramienta 
para el intercambio de correos masivos, cadenas o spam, ni de mensajes 
ofensivos, de carácter político, sexual o religioso, con fines de lucro, 
con propósitos delictivos o cualquier otro mensaje que se considere 
indebido o que vaya en contra de la Ley.

**Comment by JonnieBoy18** [comment]
Still not working

**Comment by fumu-no-kagomeko** [comment]
_ got this error when _ moved the application under ur0. Other homebrew applications execute just fine. :confused: 

Any ideas why it happens?

**Comment by kenjieXhimura** [comment]
hi ...i really need your help pro masters ... ive tried to follow the instruction here even doing it while playing the tutorial in youtube but when i have the henkaku bubble on my ps vita it keeps on saying that " Cannot start this application. You must download the application again from ps store" help pls i just updated it on 3.68 and im on windows when im doung this folder PCSG90096  

please send me email kenjieXdabon@gmail.com

or give me some info here in this page .... thank you so much guys...

**Comment by Masters110** [comment]
That  means you did something wrong. Delete all files and start over from
the beginning.

**Comment by kenjieXhimura** [comment]
ive tried it 5 times it still gave me thesame problem...but i didnt follow that step... and look for another way

ive tried  the other way of having the h-encore.... by just putting the file on my ps vita by qcma ....and install it.... just consider my thread resolved thanks hehehehe

**Comment by Masters110** [comment]
This isnt the place to ask noob questions. Wipe Everything and start over.
The error means you did something  wrong.

**Comment by este298** [comment]
Yo chill the fuck up I did it like 10 times and it ain't working. So instead of being a dick help somebody you jerk. 🖕

**Comment by Masters110** [comment]
Go and ask on gbatemp forum

**Comment by kenjieXhimura** [comment]
not gonna happen nyahhahahaha @este298

**Comment by kenjieXhimura** [comment]
just kidding .... just dont do the cmd thing ... this is a lot easier than doning thos stuffs/... go chek on youtube   type in h-encore mod for ps vita   ... sorry i cant browse anything at work right now with videos so the only thing i can help you is go to tj's page on you tube look for video thumbnail like this 
![maxresdefault](https://user-images.githubusercontent.com/41878279/43614777-7289c896-96e7-11e8-8b31-df54198a7217.jpg)

and you will surely be thankfull ive discoverd it ... its so easy to follow there will be a link on that website or try to download 

https://github.com/noahc3/auto-h-encore/releases
  and download the 
auto.h-encore.v0.4.4.zip

and fun strats from that h-encore and vita shell is already on that file 

if you cant see the file ill attach it here

[auto.h-encore.v0.4.4.zip](https://github.com/TheOfficialFloW/h-encore/files/2255375/auto.h-encore.v0.4.4.zip)


thank me after you finish this 

goodluck

**Comment by este298** [comment]
hey kenjieXhimura it worked thanks for the help man.

**Comment by kenjieXhimura** [comment]
no probs dude ... happy to help yah out ... told you it will work heheheheheh

**Comment by yeonsha** [comment]
Let me help you fix this problem as I'm facing this problem as well before.
This is what i did..
Go to vitashell. Find ur0:tai/config.txt.
In the config text you will realize there's some kerenel is missing, it happen because you have reseting "taihen" on E-hencore app.
Edit config.txt file and add this command under *KERNEL.

*KERNEL
ur0:tai/storagemgr.skprx
ur0:tai/nopdrm.skprx
ur0:tai/shellbat.suprx
ur0:tai/nopsmdrm.skprx
