### ISSUE TITLE
No h-encore bubble after power off

### ISSUE THREAD

**Issue by alphanu1** [TheOfficialFloW/h-encore#30]
After a full powercycle vita runs a database check and removes h-encore bubble. 

This makes it a tethered back as you have to connect to qcma and install the game/bullbe again.

**Comment by TheOfficialFloW** [comment]
Ehm. No. It will only remove the layout, but you will still be able to launch bittersmile.

**Comment by alphanu1** [comment]
Ok. That was an abrupt close. I not sure what caused the issue. I have now other plugins enabled yet.

I'll give you a quick bit of background. I left the vita in sleep with a game running overnight. Today I woke it up and loses a different game.

After this I simulated a battery dead/out of power. Buy holding the power button in till the vita force power off. Not shutdown. 

After this the vita powered up and refreshed the database. Once sack at the vita xmb neither h-encore nor blitter smile bubbles existed. 

It may be a rare chance of happening but non the less it did. 

I'll attempt to recreate the issue and upload a proof of video.
