### ISSUE TITLE
3.68 Cracked successfully, then how do I copy the vpk?

### ISSUE THREAD

**Issue by esrrhs** [TheOfficialFloW/h-encore#31]
thank you

**Comment by Rameron** [comment]
Through VitaShell?

**Comment by esrrhs** [comment]
yes, I dont konw how to install vpk game and software on psv

**Comment by Rameron** [comment]
Go to the settings of you VitaShell (press start in app main menu) and select the transfer mode you prefer: FTP or USB.
Then go back to main menu and press select button. If you was select USB transfer mode you should just plug to usb cable into your Vita and your PC. If you was select USB transfer mode Vita was show you the ip-address and port (1337). You need to use ftp client with anonymous access and these pair of ip-address and port to access to your Vita. Just copy *.vpk file to your Vita and then locally lauch it.

**Comment by esrrhs** [comment]
and I find fast way to install it:

> you can extract the .vpk file on your pc using whatever program you use to extract compressed files (eg .zip)

> move the extracted folder to your vita and press triangle, install folder. saved me about 300 years doing this, as the vita's read write speeds are much slower compared to a modern pc.

> a 4gb vpk file takes 1-2 hours to install on vita but only 10 min max to extract on pc.
