### ISSUE TITLE
Vita shuts down on sleep when henkaku is installed

### ISSUE THREAD

**Issue by mcmpresto** [TheOfficialFloW/h-encore#36]
So i did my initial test restarted my vita and put it into sleep mode without installing henkaku for 30min. And went back to it and it was still in sleep state no problem. Now i did my second test installed henkaku and put my ps vita to sleep and only just after 5 mins the vita shutdown and i have to do cold boot again.

**Comment by mcmpresto** [comment]
Im on psvita slim 3.68 btw

**Comment by TheOfficialFloW** [comment]
Any plugins installed?

**Comment by mcmpresto** [comment]
Gamesd
Storagemgr
Nonpdrm
Nopsmdrm
Noavls
Repatch
Ds3vita
Ds4vit
Kuio
Download enabler
Pngshot
Vflux
Shellbat
Vsh

Also im using sd2vita

**Comment by TheOfficialFloW** [comment]
So one of them is causing it lol

**Comment by mcmpresto** [comment]
Ill try to remove unnecessary pkugin and ill update you

**Comment by TheOfficialFloW** [comment]
Please don't, I facepalmed so hard, I don't think yet an other message would do good to me.

**Comment by CelesteBlue-dev** [comment]
@mcmpresto EASY : you should NEVER use gamesd AND StorageMgr at the same time.
Reason : both hooks suspend mode so it will crash shutdown PSVita.
Fix : remove the gamesd.skprx line in config.txt, save he file then reboot.

**Comment by mcmpresto** [comment]
Thabks @CelesteBlue-dev

**Comment by itsmeV24** [comment]
Excuse me, new to vita hacking. 
I have the same problem (vita restarts itself once it enters sleep mode) but I only have storagemgr, no gamesd. 
Could you please help me?

**Comment by CelesteBlue-dev** [comment]
@itsmeV24 what are the plugins in your config.txt ? On which FW are you ?

**Comment by itsmeV24** [comment]
I'm on FW 3.73
If I checked correctly, I have
storagemgr
Nonpdrm
reFOOD
repatch

**Comment by CelesteBlue-dev** [comment]
@itsmeV24 ok then I advice you open an issue in StorageMgr repository instead of this one. This is likely StorageMgr related. Try uninstalling StorageMgr to be sure it is the cause.

**Comment by itsmeV24** [comment]
Ok, thanks for the help

**Comment by starkilla14** [comment]
ItsmeV24 did you ever figure it out? I'm have the same exact issue as you? Same FW and same plugins..?

**Comment by itsmeV24** [comment]
Hi, I just downgraded to use ensu, reFood makes everything work even on
older firmware and it makes it so Hencore always works.

**Comment by nadia-al** [comment]
I am having tge sane problem, my ps vita slim is 3.73, I have h-encore2. When I put it to sleep it shuts down instead. How to fix?? 

My plugins in the config.txt
![Uploading 16110452037507658374405669759812.jpg…]()
 Please help

**Comment by alfredox123** [comment]
Just to clarify, if you are on 3.73 and using repatch plugin, this issue will happen. just disable repatch and should be working.

I think theres no fix for this on 3.73 atleast.
