### ISSUE TITLE
H-Encore does not work on Activated Devkits/Testkits

### ISSUE THREAD

**Issue by mathieulh** [TheOfficialFloW/h-encore#4]
As you can see in the picture below, the C2-12848-3 error occurs, this happens because of an existitng henkaku issue which has not been fixed in h-encore either. The details as to why this problem occurs are detailed in the issue below:

https://github.com/henkaku/henkaku/issues/96

![20180701_131434](https://user-images.githubusercontent.com/203427/42133884-801cc96a-7d31-11e8-9a9d-250881748dcb.jpg)

**Comment by nightyasen** [comment]
@mathieulh could you get it to work on an unactivated kit? I couldn’t

**Comment by TheOfficialFloW** [comment]
not interested in fixing this.

**Comment by LiEnby** [comment]
> @mathieulh could you get it to work on an unactivated kit? I couldn’t

how would you open bitter smile?
