### ISSUE TITLE
ERROR COPY APPLICATION PS VITA C0-11274-5

### ISSUE THREAD

**Issue by calaluis** [TheOfficialFloW/h-encore#45]
Hello dear, through this channel, I would like to report that I have practically tried everything to be able to copy the h-encore application in my PSVITA console, for which, after 11 seconds of finishing the copy, it generates the error C0-11274 -5.

I have even turned off and on, and I have also applied clean contacts to the memory card.

I did all the steps to the letter. I have firmware version 3.68, the same one that appears in the youtube video.

Link: https://www.youtube.com/watch?v=0Uv2Xhel3CU

Which may be?

**Comment by y0ui0u** [comment]
I have the exactly same issue, did you found how to solve it?

**Comment by Masters110** [comment]
Connect via usb instead of wifi

**Comment by y0ui0u** [comment]
I solve that, you have to delete all the files copied in QCMA and uninstall every program used and repeat all again, just paying a lot of attention in every passage, mostly on cmd passages.
