### ISSUE TITLE
Happy 1 month anniversary h-encore

### ISSUE THREAD

**Issue by the-importer** [TheOfficialFloW/h-encore#49]
It's been over 1 month since h-encore descended from the heavens to grant us the miracle of Vita hacking. The best part is that so far (knock on wood), SONY has yet to release another firmware to break this. Considering that last time, they released 3.61 10 days after Henkaku came out, that's pretty good. Then again, that was 2016 where the Vita still had some life in it, now it's almost all but dead, even in Japan.

**Comment by TheOfficialFloW** [comment]
:)
