### ISSUE TITLE
readme have a little mistake

### ISSUE THREAD

**Issue by wetor** [TheOfficialFloW/h-encore#5]
in Getting rid of the trophy warning 2
“Launch VitaShell and navigate to ux0:user/savedata/00” ==>>
“Launch VitaShell and navigate to ux0:user/00/savedata”
Think you very much!

**Comment by wetor** [comment]
ux0:user/savedata/00 ==>> ux0:user/00/savedata
in the 4,7,8

**Comment by SilicaAndPina** [comment]
:) it really could be ux0:user/xx/savedata as it can be multiple on DEX

**Comment by TheOfficialFloW** [comment]
Fixed
