### ISSUE TITLE
Didn't install HENkaku

### ISSUE THREAD

**Issue by XxM4rvxX** [TheOfficialFloW/h-encore#50]
The h-encore bootstrap works fine. I can install the Vitashell but wen i install HENkaku they say success then i go to the settings and the HENkaku menu dind't exist so i go back to h-encore and reset the taiHEN config.txt and try to reinstall the HENkaku but it's always the same. How i can fix that? By the way i had install HENkaku befor at the firmware 3.60

**Comment by FSEC-DALMASIAN** [comment]
what firmware Are you on

**Comment by XxM4rvxX** [comment]
3.68

**Comment by TheOfficialFloW** [comment]
Format your memory card

**Comment by XxM4rvxX** [comment]
Now it's working. Thank you :)
