### ISSUE TITLE
QCMA FOR MAC NOT WORKING

### ISSUE THREAD

**Issue by Samer313** [TheOfficialFloW/h-encore#51]
Qcma download for Mac is not working. "This is not the page your looking for"

**Comment by Samer313** [comment]
@TheOfficialFloW Is it temporary down or are you working on a fix mate?

**Comment by TheOfficialFloW** [comment]
It‘s not my repo so what do you want me to do?

**Comment by Samer313** [comment]
Who should I contact? Can i download Qcma for Mac elsewhere? Any other solutions?

**Comment by TheOfficialFloW** [comment]
https://github.com/codestation/qcma/releases

**Comment by Samer313** [comment]
Thank you!
