### ISSUE TITLE
ps vita with  henkaku it shuts down after being in standby mode for 14 seconds 

### ISSUE THREAD

**Issue by ElijahFerris** [TheOfficialFloW/h-encore#57]
so ive ran into this problem recently where i turn the vita off so its in standby mode and after 14 seconds it shuts down the vita. i left the vita on charge for a hour or so to make sure its not because the battery is too low but still happens. this started after i copied a game onto vitashell. ive deleted the game and any other VPKs i added around that time but it still happens. here is a link to a video of it. thanks for any help

https://www.youtube.com/watch?v=qzwqB9Tjcno&feature=youtu.be

**Comment by TheOfficialFloW** [comment]
disable your plugins.
