### ISSUE TITLE
Can't install on my 3.68 since 3.69 was released

### ISSUE THREAD

**Issue by acetippmann** [TheOfficialFloW/h-encore#59]
I'm trying to install h-encore on my vita 3.68 following the official instructions, but I can't get around the "system update" screen at the content manager stage (Yes I've tried both solutions in the readme). I think it's only become an issue since 3.69 was released.

**Comment by TheOfficialFloW** [comment]
Set DNS to 212.47.229.76

**Comment by Masters110** [comment]
Do it wired.

**Comment by acetippmann** [comment]
Was doing it wired, but the DNS worked. Thanks!

**Comment by Masters110** [comment]
You should of done it already.by.now you had.over a month.  You need to
find a way to use internet without it looking for psn. You need to find a
dns code that still works. Flow gave you one above.

**Comment by warfv** [comment]
Yes I am using that but it's not working 212.47.229.76
Store open but it won't sing up on PlayStation .(NW-2304-9) error

**Comment by Masters110** [comment]
Then find a new one.  Why are you guys such noobs. No free games for you
