### ISSUE TITLE
control vita with button options problem

### ISSUE THREAD

**Issue by manydig** [TheOfficialFloW/h-encore#62]
vita fat 100x 3g running 3.68 hencore

with the option to turn on the above setting on the vita (without booting into to hencore) i can control the live area fine using all buttons etc including the left analog, however as soon as i boot into hencore, the feature will not work. i check the settings menu, and see that the above option is still active but it will not control the live area, i un-check then re check the option, but again no dice it will not work.

i turn off the vita, and again without booting into hencore, all works fine (all buttons etc i am able to control in the live area), but as soon as i boot into hencore the setting does not work.

i believe its a problem related with the booting of hencore.

i did this too by turning off all relevant plugins too, still did not make any change to the above. could not control the live area/other things on vita using the buttons/left analog

**Comment by TheOfficialFloW** [comment]
If I understand correctly you CAN control the buttons in h-encore bootstrap menu right? But not in livearea after booting h-encore?

**Comment by manydig** [comment]
sorry for late reply, i was away in Minnesota, okay i have now done a reset on all the settings, but again same problem persists. it's like it turns itself off then stays off after booting into hencore, not sure why though. i know all my plugins are disabled, (i only  have lolicon, the mains one with hencore, and kuio/nonpdrm/psm) so i know definitely they don't cause problems even when disabling and resetting the config like you mentioned.  my 3g vita is fine, no problems running it, it is fairly new, so am not sure where or what the problem could be thats causing this. :(

**Comment by TheOfficialFloW** [comment]
Nobody is experiencing this, so I'm closing it.
