### ISSUE TITLE
C1-2738-0, files don't take the right name?

### ISSUE THREAD

**Issue by D219** [TheOfficialFloW/h-encore#63]
*Setup*:

PSV 1000, FW 3.68

Files should be at the right place:

- `h-encore/app/ux0_temp_game_PCSG90096_app_PCSG90096`:

```
configuration.psp2path  eboot.bin  resource  sce_module  sce_pfs  sce_sys  VITA_PATH.TXT
```

- `h-encore/license/ux0_temp_game_PCSG90096_license_app_PCSG90096`:

```
6488b73b912a753a492e2714e9b38bc7.rif  VITA_PATH.TXT
```

Generating the files:

```
./../psvimgtools-0.1-linux64/psvimg-create -n app -K 2ccb8070727c458ddb0fa3ff680cf92384ee5996e6a4a876a82de382548acb8d app PCSG90096/app
./../psvimgtools-0.1-linux64/psvimg-create -n appmeta -K 2ccb8070727c458ddb0fa3ff680cf92384ee5996e6a4a876a82de382548acb8d appmeta PCSG90096/appmeta
./../psvimgtools-0.1-linux64/psvimg-create -n license -K 2ccb8070727c458ddb0fa3ff680cf92384ee5996e6a4a876a82de382548acb8d license PCSG90096/license
./../psvimgtools-0.1-linux64/psvimg-create -n savedata -K 2ccb8070727c458ddb0fa3ff680cf92384ee5996e6a4a876a82de382548acb8d savedata PCSG90096/savedata
```

Execution logs: https://zerobin.net/?9edefb25e5f048df#LRjqYk4k+puRW8yc/xyS8eh+fESkpRzlK2UuqhsUuek=
(Password `hencore`)

Files generated:

```
app:
app.psvimg  app.psvmd

appmeta:
appmeta.psvimg  appmeta.psvmd

license:
license.psvimg  license.psvmd

savedata:
savedata.psvimg  savedata.psvmd
```

When uploaded to the PSVita, error C1-2738-0 on launch, after the trophy warning.

I saw a similar issue (#17), but the details are lacking.

It look like the files aren't generated correctly, but I can't see where I went wrong, could somebody enlighten me?

**Comment by D219** [comment]
@TheOfficialFloW May I have a reason why the issue was closed? I understand the issue look silly, and the explanation will look obvious once found, but I don't see the point in closing without any additionnal informations.

**Comment by TheOfficialFloW** [comment]
Sorry about that. Installation errors should be discussed on reddit or so, as mentioned in the readme. Since nobody else has still got this issue and since I‘m not willing to help on that, I‘ve closed it. There exists easy installers, see if they help.
