### ISSUE TITLE
A quick question from Dom

### ISSUE THREAD

**Issue by ratmandom** [TheOfficialFloW/h-encore#65]
Hello I really admire your work and other peoples work like this, I want to get into this scene like you - the new ps4 break through and all that amazing work that I have played with but don't know. hear me out.

OK so where do I start what key words will YouTube/research help me with? I am on codecadmy and have done a little there since I am new to learning in these deeper thoughts - I am in the tunnel with the rabbit now and I do feel it brewing to the pill (the part where I will show people who I am), I think I should start to learn assembly code some time. keywords of what I should be looking at will help?

The mentality that you guys have towards things like this I feel that love and buzz in me, I do not stop thinking all day I have been like this for a long time and I feel wise to a lot in life today and it get worse, my family has a few professors/doctors/WW2 built one of the first computers-helped with telephones-started radio signals, this runs in me. In me I feel power but I have only been doing this for a while and I do get better like a snow ball down Mount Everest or something. I would like to be apart of a team one day and enter into consoles like you guys do then leave it to others when you are exhausted doing that. so what should I do to begin with... codecadamy I am very creative in new ideas from what I have learnt that is a skill in its self you know.

Please reach out to me I am humble to this work. Is this work that intelligent or is it like getting the code that you can't bypass to reach? I think things that I would like to know E.G. how can the xbox one be hacked? is there any better hacks for the wii u then CBHC with something like BootMii/wii since those consoles are family?

and are you a part of the fail0verflow ?

Thank you for amazing work I love my vita 3.68. TBH I play persona 4 on the bus to collage(gaming course) and I love that game because I feel like they are my friends on persona 4(if you have played it 100% worth a go if not). And I hate people who doubt me and things I know a lot and don't lie and relate things with out saying them all the time.

I have many more story's like this I am very different and want to be one of the greatest, I am 24 and started this way about 2 years a go properly and its building like the snow ball I mention earlier.
Dominic Wake

**Comment by Masters110** [comment]
Closed in 3 2 1

**Comment by ratmandom** [comment]
if you want to close this at least hear me out and pm me!

just a few tips on what to look at where to start that was all I was looking for.

**Comment by TheOfficialFloW** [comment]
Start by learning C and assembly.
