### ISSUE TITLE
Bluetooth headset pairing issue

### ISSUE THREAD

**Issue by nmagod** [TheOfficialFloW/h-encore#67]
While h-encore is active, I am unable to create a new pairing connection to a Sentry BT200 headset (but four other headsets I've tried can pair fine) - the headset wasn't even recognized as available by my vita. 

However, if I restart to clear h-encore from active memory, my vita recognizes it and will pair to it - and then recognize it after enabling h-encore. I just spent a good 20 minutes pairing, restarting, deleting it from the devices, and repeating the process to verify.

**Comment by TheOfficialFloW** [comment]
Probably due to a plugin.
