### ISSUE TITLE
Adrenaline not working

### ISSUE THREAD

**Issue by Echoes921** [TheOfficialFloW/h-encore#71]
6.61 Adrenaline-6.7 doesn't open when initiating h-encore "automatically" with h-encore 2.0. Error: "Could not load_adrenaline_kernel.skprx. Please uninstall the old Adrenaline first."

The error doesn't appear and Adrenaline works fine when I initiate h-encore "manually" by pressing "R" and "Exit".

I'm in 3.68.

**Comment by TheOfficialFloW** [comment]
Can you please try the hotfix of h-encore 2.0?

**Comment by Echoes921** [comment]
Hi TheOfficialFloW! Yes, I have installed the latest fix of h-encore 2.0 after you solved the error installing vpks from VitaShell and Adrenaline still doesn't work if h-encore 2.0 is initated "automatically". Thank you so much for your work.

**Comment by TheOfficialFloW** [comment]
Test this: https://github.com/TheOfficialFloW/Adrenaline/releases/tag/v6.8

**Comment by Echoes921** [comment]
Nice! I'll try in a moment, 'cos I'm gonna make a clean installation of Adrenaline first. Thank you!
