### ISSUE TITLE
Upgrade problem - from 3.65 h-encore to 3.69/70 OFW

### ISSUE THREAD

**Issue by JigoKuu** [TheOfficialFloW/h-encore#76]
I just bought a used PS Vita Slim. It is simply wonderful and I totally fell in love with it. Unfortunately I detected that I can't use a majority of my games (both physical and digital games are affected), because right after I start them, I got error code C2-12828.

All right, I did my research and tried all tips the internet could offer (all kind of formatting, database rebuilt etc.), but nothing helps.

The truth is, this Slim used 3.65 H-encore as the previous owner told me, but I removed it. (Okay, I know I shouldn't have but I did it anyways, so just take a deep breath and keep reading the suffering of this stupid soul/head of mine, please.)

I didn't put my memory card or any of my game cartridges into the console while it was using Hencore. I didn't even log into my PSN. I removed/uninstalled Hencore (the previous owner told me how to do it), made a full factory reset, formatted its 1GB internal memory. Then when it ran on OFW, I updated to the current firmware and then log into my PSN and put my cards into it.

Could this previously installed Hencore(or its removal) be the reason that my console doesn't play some of my games? I am really desperate and couldn't think of anything to fix this problem. I asked in different forums, reddit, facebook etc. but nobody could help me. :(

If anybody knows something, help me, please!!!T____T

**Comment by RY0M43CH1Z3N** [comment]
Close this. Isn't a incident.

**Comment by CelesteBlue-dev** [comment]
"I updated to the current firmware".
3.70 isn't supported by h-encore.
You must wait a new hack, buy your games or buy a hackable vita.
