### ISSUE TITLE
After henkaku install cant get back into h-encore

### ISSUE THREAD

**Issue by Zeepblok** [TheOfficialFloW/h-encore#79]
Hi,

I installed henkaku via h-encore but forgot vitashell. only now I cant get back into h-encore, it keeps blinking purple and closing (after this i have the henkaku options in my menu) or the whitescreen crash.  How can I get back into the menu to install vitashell ?

**Comment by TheOfficialFloW** [comment]
Hold R

**Comment by Zeepblok** [comment]
thnx :)
