### ISSUE TITLE
When is the vita shell update for 3.70 Fw

### ISSUE THREAD

**Issue by 3mmfire** [TheOfficialFloW/h-encore#83]

**Comment by 3mmfire** [comment]
I want to hack my ps vita but i have 3.70 FW

**Comment by Masters110** [comment]
Wait till its released ffs

**Comment by TheOfficialFloW** [comment]
Seriously, people continue like that and I‘ll just drop it.

**Comment by lanner** [comment]
hello, you know that sometimes some people have brains not clear, do not penalize the real people who follow you and waiting quietly, it would be a pity for the good community 🖖

**Comment by lanner** [comment]
> Seriously, people continue like that and I‘ll just drop it.

hello, you know that sometimes some people have brains not clear, do not penalize the real people who follow you and waiting quietly, it would be a pity for the good community 🖖
