### ISSUE TITLE
How to uninstall h-encore?

### ISSUE THREAD

**Issue by L1cardo** [TheOfficialFloW/h-encore#85]
My PSVita has some problems and I want to uninstall h-encore completely.
I want to delete all my files, format memory to make my PSVita fresh clean and then reinstall h-encore.
So how to uninstall h-encore or can I just format with h-encore installed ? Won’t it cause any issues formatting with h-encore installed?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by Masters110** [comment]
Yeah. Not sure why you still use that when you can do enzo.

**Comment by L1cardo** [comment]
I have lots of problems on my device.
I just want to do it over.

**Comment by Masters110** [comment]
Its closed now. Because this isn't the place to ask noob questions

**Comment by L1cardo** [comment]
Noob？
Are you expecting everyone an expert?
Funny that whether restoring a device with a hack would cause problems or not is a noob question.
Sorry that I am not an expert, it is my bad not being an expert.

**Comment by Masters110** [comment]
Its thefloWs rules not mine.
