### ISSUE TITLE
Vita slim downgraded from 3.70 to 3.65 can't launch h-encore (crashes after white and purple screen)

### ISSUE THREAD

**Issue by mave007** [TheOfficialFloW/h-encore#87]
Just got a PS Vita Slim (PCH-2000ZA23) Japanese Ver.

Used modoru to downgrade from 3.70 to 3.65 (system can not be downgraded further) and followed the [Readme step by step](https://github.com/TheOfficialFloW/h-encore/blob/master/README.md) up to step 12 without issues.

Once I run `h-encore` the white and purple screen appears, and the the app unexpectedly quits. I don't know if I can read logs nor to search what's the reason of the fail. 

Any tips?

**Comment by TheOfficialFloW** [comment]
Hold R while booting h-encore.

**Comment by ErickSavior** [comment]
Can u help me ?
how to Change THe Bottom R to press L While Booting ?
i'll write it by myself , i want to learn ... please

**Comment by KatyushaScarlet** [comment]
Thanks!
Same problem, that helps a lot!
